name: Deploy pos-salafan to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch: {} # allow manual run from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy pos-salafan
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} "bash /root/srv/pos-salafan/deploy.sh"
